development:
  adapter: mysql
  database: partmachine_development
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 8889

test:
  adapter: mysql
  database: partmachine_test
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 8889

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
